-- Create the projects table
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  category TEXT,
  "shortDescription" TEXT,
  description TEXT,
  "coverImage" TEXT,
  "galleryImages" TEXT[],
  "createdAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Create policies for public access
-- This policy allows anyone to view all projects
CREATE POLICY "Public projects are viewable by everyone."
  ON projects FOR SELECT
  USING ( TRUE );

-- These policies allow anyone to insert, update, or delete projects.
-- For a production app, you would want to restrict these to authenticated users.
CREATE POLICY "Anyone can insert a new project."
  ON projects FOR INSERT
  WITH CHECK ( TRUE );

CREATE POLICY "Anyone can update projects."
  ON projects FOR UPDATE
  USING ( TRUE );

CREATE POLICY "Anyone can delete projects."
  ON projects FOR DELETE
  USING ( TRUE );
